# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
MACHINE_NAME = "hhbd-app-vmx"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Fix to: https://github.com/mitchellh/vagrant/issues/1673
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    config.ssh.forward_agent = true

    config.omnibus.chef_version = :latest
    config.berkshelf.enabled = true
    config.berkshelf.berksfile_path = "Berksfile"

    config.vm.box = "ubuntu/trusty64"
    config.vm.hostname = MACHINE_NAME
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider "virtualbox" do |vb|
        vb.name = MACHINE_NAME
    end

    # Configure networking
    config.vm.network :private_network, ip: "192.168.99.99"

    # Configure synced directoires
    config.vm.synced_folder "../www", "/var/www/hhbd-app"
    config.vm.synced_folder "../../hhbd.pl-content/s.hhbd.pl", "/var/www/s.hhbd.pl"

    # Configure provisioning
    config.vm.provision "chef_solo" do |chef|

        chef.roles_path = "./roles"
        chef.add_role "dev"
        # chef.log_level = :debug
    end
end
